name: Renovate config validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LOG_LEVEL: debug

jobs:
  validate-config:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: lts/*

      - name: Run npx
        run: >-
          npx -p renovate -c
          'renovate-config-validator
          default.json
          renovate-config.json
          renovate.json
          '
