name: Renovate config validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LOG_LEVEL: debug

jobs:
  validate-config:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js environment
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: lts/*

      - name: Run npx
        run: >-
          npx -p renovate -c
          'renovate-config-validator
          default.json
          renovate-config.json
          renovate.json
          '
